### ISSUE TITLE
Component > Button

### ISSUE THREAD

**Issue by anneguo3** [nwplus/CMS-V2#100]
Update existing button to reflect all necessary types (path to current file: components/Assessment/Button.js)

Add in default, hover/click state and inactive for following buttons and add rounded version of the buttons

- [ ] Primary
- [ ] Secondary
- [ ] Outline
- [ ] Destructive
- [ ] No Background

<img width="320" alt="Screen Shot 2021-10-28 at 8 33 38 PM" src="https://user-images.githubusercontent.com/40816838/139354286-ff48f7a5-5fc2-4557-a74e-03541b5edbe4.png">

<img width="870" alt="Screen Shot 2021-10-28 at 8 37 25 PM" src="https://user-images.githubusercontent.com/40816838/139354529-d07c5781-8196-4e90-a196-5a50a2eb14d1.png">

Figma reference: https://www.figma.com/file/vmZ1jRhhLHZDcY6rcrWYT2/Aurora-Design-System?node-id=722%3A87

**Comment by dchen150** [comment]
@anneguo3 
is there a different figma link?
![image](https://user-images.githubusercontent.com/45786074/140448379-a127759f-5167-41ed-86e6-4d15ee809c0e.png)
